services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    ports:
      - "8080:80"
    environment:
      - "TZ=Europe/Luxembourg"
      - "NODE_ENV=production"
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - postgres
    env_file:
      - ./backend/.env.production
    secrets:
      - POSTGRES_USER
      - POSTGRES_PW
      - WEBTOKEN_SECRET
      - CAM_USER
      - CAM_PW
      - PRUSAAPIKEY
    environment:
      - "TZ=Europe/Luxembourg"
      - "NODE_ENV=production"
    healthcheck:
      test: "/usr/local/bin/nodejs /home/oto/app/healthcheck"
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always

  tasks:
    build:
      context: ./tasks
      dockerfile: Dockerfile
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
    depends_on:
      - postgres
      - redis
    ports:
      - "5600:5500"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PW
      - REDIS_PW
      - WEBTOKEN_SECRET
      - FLASK_SECRET
      - SSH_KEY_DOCKER_HOST
    environment:
      - "TZ=Europe/Luxembourg"
      - "FLASK_ENV=production"
      - "WORKER_IMAGE_TAG=oto_worker:alpha"
    env_file:
      - ./tasks/.env.production
    healthcheck:
      test: curl --fail -s http://localhost:5500/tasksapi/version || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
    restart: always

  postgres:
    image: postgres:14.3-alpine3.15
    ports:
      - "5432:5432"
    secrets:
      - POSTGRES_USER
      - POSTGRES_PW
    environment:
      POSTGRES_USER_FILE: /run/secrets/POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PW
      POSTGRES_DB: oto
      TZ: Europe/Luxembourg
    volumes:
      - postgres:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    secrets:
      - REDIS_PW
    environment:
      TZ: Europe/Luxembourg
      REDIS_PASS_FILE: /run/secrets/REDIS_PW
    command: [
      "bash", "-c",
      '
       docker-entrypoint.sh
       --requirepass "$$(cat $$REDIS_PASS_FILE)"
      '
    ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  # In dev we start a worker immediately via docker-compose to make development easier
  worker:
    deploy:
      replicas: 0
    build:
      context: ./tasks
      dockerfile: ./worker/Dockerfile
    image: oto_worker:alpha
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./tasks/worker/.env.production
    # In prod it is tasks that starts worker and injects secrets into env. In dev new workers also follow that way
    secrets:
      - POSTGRES_USER
      - POSTGRES_PW
      - REDIS_PW
      - FLASK_SECRET
      - SSH_KEY_DOCKER_HOST
    environment:
      - QUEUES=single,scheduled
      - WORKER_NAME_SUFFIX=dev_docker_host  # docker host that worker will look for to be able to start new containers
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      device: /home/chris/oto/postgres
      o: bind

secrets:
  SSH_KEY_DOCKER_HOST:
    # Used by tasks service to launch worker dockers on docker host
    # Used by workers themselves to start docker pipelines on docker host
    file: ./secrets/certificates/id_rsa_dev

  # passwords
  POSTGRES_USER:
    file: ./secrets/passwords/POSTGRES_USER
  POSTGRES_PW:
    file: ./secrets/passwords/POSTGRES_PW
  REDIS_PW:
    file: ./secrets/passwords/REDIS_PW
  WEBTOKEN_SECRET:
    file: ./secrets/passwords/WEBTOKEN_SECRET
  FLASK_SECRET:
    file: ./secrets/passwords/FLASK_SECRET
  CAM_USER:
    file: ./secrets/passwords/CAM_USER
  CAM_PW:
    file: ./secrets/passwords/CAM_PW
  PRUSAAPIKEY:
    file: ./secrets/passwords/PRUSAAPIKEY