version: '3'
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "80:4200"
    environment:
      - "TZ=Europe/Luxembourg"
      - "NODE_ENV=production"
